# CMake generated Testfile for 
# Source directory: /home/clme1717/Git/dbAccess/libs/mariadb/mariadb-connector-c-3.0.2-src/unittest/libmariadb
# Build directory: /home/clme1717/Git/dbAccess/libs/mariadb/mariadb-connector-c-3.0.2-src/unittest/libmariadb
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(bulk1 "/bulk1")
set_tests_properties(bulk1 PROPERTIES  TIMEOUT "120")
add_test(performance "/performance")
set_tests_properties(performance PROPERTIES  TIMEOUT "120")
add_test(basic-t "/basic-t")
set_tests_properties(basic-t PROPERTIES  TIMEOUT "120")
add_test(fetch "/fetch")
set_tests_properties(fetch PROPERTIES  TIMEOUT "120")
add_test(charset "/charset")
set_tests_properties(charset PROPERTIES  TIMEOUT "120")
add_test(logs "/logs")
set_tests_properties(logs PROPERTIES  TIMEOUT "120")
add_test(cursor "/cursor")
set_tests_properties(cursor PROPERTIES  TIMEOUT "120")
add_test(errors "/errors")
set_tests_properties(errors PROPERTIES  TIMEOUT "120")
add_test(view "/view")
set_tests_properties(view PROPERTIES  TIMEOUT "120")
add_test(ps "/ps")
set_tests_properties(ps PROPERTIES  TIMEOUT "120")
add_test(ps_bugs "/ps_bugs")
set_tests_properties(ps_bugs PROPERTIES  TIMEOUT "120")
add_test(sp "/sp")
set_tests_properties(sp PROPERTIES  TIMEOUT "120")
add_test(result "/result")
set_tests_properties(result PROPERTIES  TIMEOUT "120")
add_test(connection "/connection")
set_tests_properties(connection PROPERTIES  TIMEOUT "120")
add_test(misc "/misc")
set_tests_properties(misc PROPERTIES  TIMEOUT "120")
add_test(ps_new "/ps_new")
set_tests_properties(ps_new PROPERTIES  TIMEOUT "120")
add_test(sqlite3 "/sqlite3")
set_tests_properties(sqlite3 PROPERTIES  TIMEOUT "120")
add_test(thread "/thread")
set_tests_properties(thread PROPERTIES  TIMEOUT "120")
add_test(features-10_2 "/features-10_2")
set_tests_properties(features-10_2 PROPERTIES  TIMEOUT "120")
add_test(dyncol "/dyncol")
set_tests_properties(dyncol PROPERTIES  TIMEOUT "120")
add_test(async "/async")
set_tests_properties(async PROPERTIES  TIMEOUT "120")
